#pragma once

enum {
    DUO_OPCODE_UNDEFINED,

    DUO_OPCODE_PUSH_IDENT,
    DUO_OPCODE_PUSH_STRING,
    DUO_OPCODE_POP,

    DUO_OPCODE_CALL,

    DUO_OPCODE_OPEN,

    DUO_OPCODE_ASSIGN,

    DUO_OPCODE_ADD,
    DUO_OPCODE_SUB,
    DUO_OPCODE_MUL,
    DUO_OPCODE_DIV,
    DUO_OPCODE_MOD,
    
    DUO_OPCODE_POS,
    DUO_OPCODE_NEG,

    DUO_OPCODE_AND,
    DUO_OPCODE_OR,
    DUO_OPCODE_XOR,
    DUO_OPCODE_NOT,

    DUO_OPCODE_BAND,
    DUO_OPCODE_BOR,
    DUO_OPCODE_BXOR,
    DUO_OPCODE_BNOT,

    DUO_OPCODE_BSHL,
    DUO_OPCODE_BSHR,
};